### ISSUE TITLE
Tasks view command showing completed tasks 

### ISSUE THREAD

**Issue by TorgeirCook** [BRO3886/gtasks#1]
Hi! 

When I run the `tasks view` command with the -c flag I get all tasks, even the ones with status: completed. 

### Terminal output 
```properties
gtasks tasks view -c=false


Tasks in i2a:
[1] Test
    Description: 
    Status: completed
    No Due Date
[2] Add http -> https rule for DC
    Description: 
    Status: completed
    No Due Date
[3] Sjekke om vi trenger databehandler avtale og send til Tommy Lund
    Description: 
    Status: completed
    No Due Date
[4] Send refusjon om apple utvikler lisens til Vemun
    Description: 
    Status: needsAction
    No Due Date
[5] Update xplore doc with mqtt implementation
    Description: 
    Status: completed
    No Due Date

```

**Comment by BRO3886** [comment]
Thank you, I'll check out what's wrong

**Comment by BRO3886** [comment]
Meanwhile, if you want to take up this issue do let me know @TorgeirCook

**Comment by TorgeirCook** [comment]
Thanks! I haven't worked with GO before so it will be difficult for me to solve this.

**Comment by BRO3886** [comment]
So, the -c flag should **only be included** when you want to see the completed tasks. If you don't include the `--completed` flag **it will show the pending tasks**.

The way it's designed is that the command checks for the presence of `--completed` and then sets it to `true` or `false`.

Example: 
```bash
gtasks tasks view
```
* Will show incomplete tasks
```bash
gtasks tasks view --completed
```
* Will also include completed tasks

I think I should update this flag to reflect that this is used when you want to include completed tasks.

```bash
gtasks tasks view --include-completed
```
This would probably be better I guess.

The `--completed` flag should be repurposed for filtering only completed tasks. 

Thank you for using the CLI. I hope this solves your issue. I'll update the flags.

**Comment by TorgeirCook** [comment]
Great stuff! I stil get completed tasks when running with out any flags on version 0.9.1 though :/ 

`gtasks tasks view`

**Comment by BRO3886** [comment]
Yeah I am still debugging that. Maybe I'll remove programmatically instead of relying on the api

**Comment by BRO3886** [comment]
Fixed, pushing soon.
