### ISSUE TITLE
Tasks and tasklists create/add commands are inconsistent

### ISSUE THREAD

**Issue by mxbees** [BRO3886/gtasks#11]
I was going to do a pull request to update the documentation for tasks, to swap 'create' for 'add' to match the command but looking at tasklists, I see that the command for a new one is 'create'.

Perhaps not the biggest issue, I realize, but having the same command for new tasks and tasklists would be good for new users (it'll be easier to remember).

I don't know go, so I don't want to muck around in the code, but I could help with updating the documentation, if you'd like.

**Comment by BRO3886** [comment]
I see, thank you for pointing this out. Will update. I'll let you know if I need any help with the documentation ✌

**Comment by BRO3886** [comment]
fixed in 0.9.7
