### ISSUE TITLE
Create new task without prompt.

### ISSUE THREAD

**Issue by spike1234** [BRO3886/gtasks#13]
Hi!
I'd like to create a new task without prompt.

Maybe you could add some flags, for example:

`gtasks tasks add --tasklist "my list" --title "my title" --note "my notes" --due "2021-09-15"`

**Comment by BRO3886** [comment]
Would you like to take this up?

**Comment by spike1234** [comment]
> 
> 
> Would you like to take this up?

If you mean to write code for this, I am sorry, but I don't know GO language... 
:-)
