### ISSUE TITLE
Different sort order in gtasks and than in the official Android Tasks and web app 

### ISSUE THREAD

**Issue by TorgeirHeim** [BRO3886/gtasks#17]
When changing the order of tasks in the Android or web app, the changes are not reflected in gtasks:

![Screenshot from 2021-10-22 09-42-29](https://user-images.githubusercontent.com/1838311/138414146-40c3d7a7-5317-4824-9a5f-587abe1e2fa8.png)

![Screenshot from 2021-10-22 09-40-34](https://user-images.githubusercontent.com/1838311/138414167-6470a617-5577-41be-ba3d-393105c3a424.png)

![Screenshot_20211022-094244_Tasks](https://user-images.githubusercontent.com/1838311/138414254-6c1d799f-16b3-4522-81a5-d1a0bbafd29a.jpg)

**Comment by BRO3886** [comment]
I'll check up on this. I'm showing directly from API. I think it orders based on creation timestamp. Thanks.
